### ISSUE TITLE
Excel Ribbon: Custom Tab Disappears

### ISSUE THREAD

**Issue by MikeEburne** [fernandreu/office-ribbonx-editor#101]
Bug Description
I have been using the product some quite some time without any issues. However, recently the custom tab created in Excel 2016 disappears for some users. The user experience is, when a user opens one of my spreadsheets, the customised tab 'Mantis Networks' is not there. This is problematic as my spreadsheets are all protected and the user need to run an 'open' routine from the missing tab.

I have attached a text file with my code, a spreadsheet with the tab intact and one with the tab missing.

[Missing Custom Tab Issue.zip](https://github.com/fernandreu/office-ribbonx-editor/files/4728353/Missing.Custom.Tab.Issue.zip)

I cannot for certain confirm this but it appears that a common denominator for users experiencing this may be that they are opening the file from a shared folder such as SharePoint or Drop Box.

I can be contacted in South Africa on +27836021202 or via email mike@mantisnetworks.co.

Mike Eburne

**Comment by fernandreu** [comment]
Hi Mike,

I am not sure if I fully understand why you have two spreadsheets. Is the `Intact` file the one you saved with the Office RibbonX Editor, and the `Missing` file the one that your users end up seeing somehow?

When you unzip it, the `Missing` file does not contain the `customUI` folder that holds the corresponding UI, icons, etc., so this is clearly why you do not see that tab. There is, however, an extra `customXml` folder, not sure why or what is its purpose (it is not something the Office RibbonX Editor would generate on its own either).

Perhaps there was some antivirus / spam filter or similar altering the file, although I would find that a bit odd (it would be more common for them to delete the entire file).

![image](https://user-images.githubusercontent.com/2480661/83788919-e0c7a000-a68d-11ea-843b-b369b78d3447.png)

**Comment by MikeEburne** [comment]
Hi Fernando,

1. Would it be at all possible for us to have a telephone or Zoom
conversation? I am still experiencing issues with missing custom tabs on
the Office Ribbon in Excel spreadsheets.

2. I have one particular spreadsheet that will not display the custom
tab even after I have inserted the code again.I have attached a zip folder
containing the following:
a) The Excel file I have having trouble with
b) A txt file containing the code
c) Two custom images

FYI - I have even uninstalled the Office RibbonX Editorand reinstalled it
using the OfficeRibbonXEditor-NETFramework.msi installation app from
GitHub. This made no difference.

I can be contacted on my mobile using +27836021202 - or on Zoom using
mike@mantisnetworks.co

Regards



The contents of this e-mail and any attachments are confidential, may be
privileged and are intended solely for the use of the named recipient(s).
If you have received it in error, do not disclose, distribute, or retain it
or any part of it, and please notify the sender immediately and delete the
e-mail.

**Comment by fernandreu** [comment]
Hi Mike,

I think you attached files via email, but those are deleted on the GitHub thread; you would need to attach these via the GitHub website instead.

Anyway, I think you are experiencing the same issue as being described here:
https://answers.microsoft.com/en-us/msoffice/forum/all/custom-ribbon-tabs-gone-from-excel-files/b6c44a41-bb68-482a-a20a-2e4f676c1a10
Click on Replies to see the full thread, which might be more interesting than the accepted solution.

It is quite a recent thread with many users affected, so all seems to indicate that an update in OneDrive / SharePoint might be causing the issues.

In that thread there are a few workarounds that might or might not work for you (I cannot test them unfortunately), from copying some files manually inside the .xlsm file to [changing some setting in OneDrive](https://support.office.com/en-us/article/Use-Office-applications-to-sync-Office-files-that-I-open-8a409b0c-ebe1-4bfa-a08e-998389a9d823). I would suggest giving them a go first and see how it goes.

Depending on that, I could potentially make some changes to the way files are saved in the `Office RibbonX Editor` if that ends up being a good workaround for the issue. As things stand, however, it seems the files are being created correctly from the tool, but corrupted in OneDrive / SharePoint (i.e. same thing would occur if you did not use the tool at all and you added the customUI.xml file manually).

**Comment by MikeEburne** [comment]
Hi Fernando,

Thank-you. What people in the thread are reporting is exactly my
experience. I appreciate the feed-back.

In the meantime I have instructed all my clients to download the file to
the local C drive first and then upload again once they are finished
working.

Regards

Mike



The contents of this e-mail and any attachments are confidential, may be
privileged and are intended solely for the use of the named recipient(s).
If you have received it in error, do not disclose, distribute, or retain it
or any part of it, and please notify the sender immediately and delete the
e-mail.

**Comment by fernandreu** [comment]
Just closing this issue for a bit of housekeeping, but feel free to comment if there is anything I could do from the tool side at some point.
