### ISSUE TITLE
Runtime Error (at 10:171) Out of Range

### ISSUE THREAD

**Issue by GeoWells** [fernandreu/office-ribbonx-editor#107]
I am getting the error message "Runtime Error (at 10:171) Out of Range" during the installation. I have tried all versions and get the same error in each. I am using Windows 10. I have the latest .Netframework installed.

**Comment by fernandreu** [comment]
Hi GeoWells,

I cannot reproduce the issue if I try the installers myself. Could you give a few more details?

1. Is this a fresh installation or are you installing it over an already existing version of the tool?
    a. If it is a fresh installation, which installation location did you choose?
    b. If it is an upgrade, does it work if you uninstall the previous version and try to install it again?
2. Did you choose to create a start menu folder? If so, with name did you give to that folder?
3. Did you choose to create a desktop shortcut?
4. Is there any more info in the error message, or does it occur at a specific point of the installation process? A screenshot for this might help

**Comment by fernandreu** [comment]
Thanks for the info, I can reproduce it now. The installer type changed from 1.6 to 1.7, so something must be going wrong when trying to uninstall the previous version. I will fix that, but glad to know it works when you uninstall that version manually in the meantime.
