### ISSUE TITLE
Missing generated callback for DropDown getSelectedItemID 

### ISSUE THREAD

**Issue by jdmsdev** [fernandreu/office-ribbonx-editor#118]
**Describe the bug**

The 'Generate Callbacks' function does not generate a callback signature for the 'getSelectedItemID' callback function for a DropDown.

**To Reproduce**

Create DropDown using following XML

<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui">
	<ribbon >
		<tabs>
			<tab id="myTab" 
				label="My Tab" 
				insertAfterMso="TabHome">
        			<group id="myGroup" 
						label="My Group">
                    <dropDown id="myDropDown" 
                            label="My DropDown"
                            onAction="RibbonCallbacks.dropDownOnAction"
                            getEnabled="RibbonCallbacks.dropDownGetEnabled"
                            getSelectedItemID="RibbonCallbacks.dropDownGetSelectedItemID">
                        <item id="One" label="One" />
                        <item id="Two" label="Two" />
                        <item id="Three" label="Three" />
                        <item id="Four" label="Four" />
                        </dropDown>
        			</group>
      		</tab>
    		</tabs>
  	</ribbon>
</customUI>

**Expected behavior**

A callback signature for the getSelectedItemID callback function

**Additional context**

Note that if getSelectedItemID is changed to a getSelectedItemIndex callback function, then a callback signature is generated for that function.

**Version info**

Version: 1.7.1.886
Runtime:
 .NET Framework 4.8.4250.0
 Operating System: Microsoft Windows 10.0.19041

**Comment by fernandreu** [comment]
Hi, thanks for letting me know. The issue was that the method scanning the xml code was expecting <code>getSelectedItemI<b>d</b></code> (with lowercase d), which is incorrect. Same issue with <code>getItemI<b>d</b></code>. It should be fixed in [this build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=909&view=artifacts&type=publishedArtifacts).
