### ISSUE TITLE
Submit bug button produces garbage text

### ISSUE THREAD

**Issue by nbelyh** [fernandreu/office-ribbonx-editor#132]
**Describe the bug**
The "submit button" produces garbage text in the "submit bug" form (see screenshot below)

**To Reproduce**
Try to click "Submit bug" report if you encounter an issue (ex: #131)

**Expected behavior**
Some readable text is put to the form

**Screenshots**

![image](https://user-images.githubusercontent.com/528366/102024584-385c6c00-3d93-11eb-888b-e9b894c5c6ec.png)

![image](https://user-images.githubusercontent.com/528366/102024585-401c1080-3d93-11eb-91a3-15e11e67bfdd.png)

**Additional context**
There is double-encoding. 

First you escape here:
https://github.com/fernandreu/office-ribbonx-editor/blob/3d587b0dddfab82b1b123ba8b8b29f2670ee9517/src/OfficeRibbonXEditor/ViewModels/Dialogs/ExceptionDialogViewModel.cs#L49-L50

And then here one more time:
https://github.com/fernandreu/office-ribbonx-editor/blob/3d587b0dddfab82b1b123ba8b8b29f2670ee9517/src/OfficeRibbonXEditor/Services/UrlHelper.cs#L20-L21

**Comment by fernandreu** [comment]
Yeah you are right, I must have refactored the code and not realised I was doing the encoding in both the call and the new method. Fixed in [this build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=966&view=artifacts&pathAsName=false&type=publishedArtifacts).
