### ISSUE TITLE
Application crashes on Visio files

### ISSUE THREAD

**Issue by nbelyh** [fernandreu/office-ribbonx-editor#133]
**Is your feature request related to a problem? Please describe.**
I try to use the editor to modify [Microsoft Visio](https://www.microsoft.com/en/microsoft-365/visio/flowchart-software) file actually 😄 
The application crashes although VSDX, VSDM, etc are **valid office open xml files**, and Visio is part of Microsoft Office family.
Any Microsoft sample file will do (with vsdx extension)

**Describe the solution you'd like**
I expect the application to works for Visio files the same way it does for the rest of the office applications 😄 

**Screenshots**
![image](https://user-images.githubusercontent.com/528366/102025147-48297f80-3d96-11eb-9e6a-99dceb805119.png)

**Comment by fernandreu** [comment]
Thanks for submitting the issue!

Just one comment: it shouldn't actually crash in the builds from the GitHub Releases page or from Azure Pipelines, given they should be done with the Release configuration and those Debug.Assert lines should be stripped out. Perhaps you did your own debug build after fixing #131 locally?

I'll fix it regardless, also adding Visio file types to the dropdown list in the open / save file dialogs.

**Comment by nbelyh** [comment]
Therefore this is not a bug but feature request 😄

**Comment by nbelyh** [comment]
@fernandreu added PR to support Visio files... Please kindly check if it's okay.
