### ISSUE TITLE
Installation Warning (v1.8)

### ISSUE THREAD

**Issue by bitaller** [fernandreu/office-ribbonx-editor#143]
Hi,

I got the warning when I tried to install v1.8 on Windows 10. Both NET5 and NETFramework have same warning. v1.7 doesn't have the same issue. 

![202012_06](https://user-images.githubusercontent.com/36088974/106370074-b822a380-630b-11eb-85ed-6fa92ca9ea52.png)

Windows has protected your computer
Microsoft Defender SmartScreen prevented unrecognized apps from launching. Running this application may put your computer at risk.

**Comment by fernandreu** [comment]
Hi bitaller, this is actually normal. The files are digitally signed, but it seems it takes some time for Windows to trust new versions of those. So, this SmartScreen window will keep popping up until there have been a few downloads / installations of the tool (I'm not sure how many are needed exactly). This is also the first release I do with a different certificate I am using from now on, which might be a factor on this.

You should still be able to bypass this by clicking on `More info` (if that's what I think it says) and then clicking on the new `Run anyway` button that will appear at the bottom. I can ensure you there's nothing suspicious about the tool; the build comes straight from Azure Pipelines, using only the code you can see on this repo.

**Comment by bitaller** [comment]
Got it. The new release is awesome. It autmatically set the language of software with Windows region setting.  
btw, I found #142 was integrated in the new release except for "Translators".

![202101_39](https://user-images.githubusercontent.com/36088974/106394441-73e9de80-63b1-11eb-9f5c-011b01435f5b.png)

**Comment by fernandreu** [comment]
Oops, I created the entry to be translated but forgot to actually use it inthe About dialog. Thanks for pointing that out. I will fix it but perhaps I won't update the release just for this, given it is just a minor visual thing.
