### ISSUE TITLE
Does your Ribbon Editor work with Access?

### ISSUE THREAD

**Issue by Godti** [fernandreu/office-ribbonx-editor#151]
I have used the Ribbon editor for excel no issues, love it.  But I was wondering if I could use for Access?

**Comment by fernandreu** [comment]
Hi Godti,

Hi have no experience using custom UIs in Access but, by the looks of this, it seems it is something you embed in the database itself?
https://support.microsoft.com/en-us/office/create-a-custom-ribbon-in-access-45e110b9-531c-46ed-ab3a-4e25bc9413de

If that is the case, I'm afraid this editor won't be of much help, given that all the process can / should be done within Access itself (it seems). The database file format isn't the same as in the other Office apps (i.e. it's not a `.zip` file), so trying to support this from the tool would also be very challenging.

Hence, you wouldn't be able to use the main selling point of this tool, which is being able to unzip that file, insert / update the XML code, then zip the file back. However, the XML namespace seems to be the same though, so you could still use some of the auxiliary features from the tool. For example, you could copy the XML code to a temporary file in the editor to double-check the syntax, validate it, insert a sample, etc., then copy the result back to Access. But nothing as streamlined as for the other Office apps.
