### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by carpac** [fernandreu/office-ribbonx-editor#154]
Hi folks,

I took the strings.resx file and created a german translation. As I am not familiar with GitHub, I attach the file to this issue.
[Strings.de.resx.txt](https://github.com/fernandreu/office-ribbonx-editor/files/6336133/Strings.de.resx.txt)
(Rename Strings.de.resx.txt to Strings.de.resx)

Regards, Carsten

**Comment by fernandreu** [comment]
Hi Carsten,

Thanks a lot for the translation, much appreciated! I've added this to the tool already:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1023&view=artifacts&pathAsName=false&type=publishedArtifacts

For now, I've added your username together with your GitHub profile page to both the About dialog of the tool and the README of this project ([here](https://github.com/fernandreu/office-ribbonx-editor#special-thanks-to-all-translators-so-far)). Happy to change any of these to something you might prefer instead.
