### ISSUE TITLE
Question: Can I enable built in customization to manipulate my customUI ribbon?

### ISSUE THREAD

**Issue by jasell** [fernandreu/office-ribbonx-editor#157]
Hi,
Sorry for posting a question here but I haven’t found a forum for this excellent tool.

I have built ribbon add-ins for word/excel/ppt to my organization. Before distributing them to all I test them on a small group.

One feedback I got was that some user wanted to change the position of the new tab I introduced in the ribbon. They thought they could do this from File/Option/Customize Ribbon. But the new tab is not visible there.

Is there a way to enable the customUI ribbon in the options/customization tool?

As of now I can only see that user can disable the complete add-in for Excel or PowerPoint. For word they need to replace the normal.dotx file.

**Comment by fernandreu** [comment]
Hi jasell,

It seems it's as you say for me too. I don't see the custom tabs in the Customize Ribbon section.

The best workaround that occurs to me is to use the `insertAfterMso` attribute to specify a tab you don't mind moving around, and move that tab instead. For example, in my Excel version, there's a *Background Removal* that I've never seen, so I wouldn't mind moving it left or right:

```xml
<tab id="customTab" label="Contoso" insertAfterMso="TabBackgroundRemoval">
```

Perhaps there's a way for this to work with custom tabs you create within Office itself (in that same dialog). If so, you could create a dummy custom tab this way but keep it hidden. Hence, it wouldn't matter where you put it, except for your custom UI file, which would be placed relative to it. I am unsure this would work though, as I don't see a way of referencing the name / ID of this custom tab in XML, but it might be worth investigating.
![image](https://user-images.githubusercontent.com/2480661/116869652-01370c00-ac09-11eb-87b7-0c504d6aa2b6.png)

This might be another workaround for you: place the add-in relative to another dummy add-in, so you can distribute your colleagues different dummy add-ins depending on where they want the actual add-in to appear:
https://stackoverflow.com/questions/53009245/excel-customui-ribbon-placement-next-to-another-customui-ribbon-tab

**Comment by jasell** [comment]
Great work around, I use insertAfterMso="TabBackgroundRemoval" as you suggest, and it exist in the same way for all PTP, Excel, word... so at least it is consistent.

**Comment by fernandreu** [comment]
Glad it helped!
