### ISSUE TITLE
Context Menu Command Incorrect

### ISSUE THREAD

**Issue by zorvek** [fernandreu/office-ribbonx-editor#169]
The context menu command "Edit with OfficeRibbonXEditor" created in the Registry references the dll, not the exe:

"C:\Program Files\Office RibbonX Editor\OfficeRibbonXEditor.dll" "%1"

It should be:

"C:\Program Files\Office RibbonX Editor\OfficeRibbonXEditor.exe" "%1"

**Comment by fernandreu** [comment]
Hi zorvek, thanks for letting me know and sorry for the late reply. The bug should be fixed in this build:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1037&view=artifacts&pathAsName=false&type=publishedArtifacts
