### ISSUE TITLE
Translation support volunteer (French and Dutch) - but need help with Github process

### ISSUE THREAD

**Issue by pplanch** [fernandreu/office-ribbonx-editor#175]
Fernando,

As mentioned earlier, I'd be happy to provide some translation support (I'm native in Dutch and fluent in French).

I am a complete novice in Github and would need some help in getting to the source files (English I presume ?) from which to start my translations, and some guidance on where to store my "output" ?

Thanks

**Comment by fernandreu** [comment]
Hi @pplanch, thanks for volunteering!

I think it will be easier in this case if I just provide you the file to be translated here and, once translated, you pass it back as a reply here as well. After that, I can take care of doing the GitHub side of it and incorporate the translations to the tool.

Essentially, the file to be translated is [this one](https://github.com/fernandreu/office-ribbonx-editor/blob/master/src/OfficeRibbonXEditor/Resources/Strings.resx). Here is that same file attached to this post: [Strings.resx.txt](https://github.com/fernandreu/office-ribbonx-editor/files/7001566/Strings.resx.txt).

In the file, you will see lots of entries such as this:

```xml
  <data name="Message.CloseUnsavedDoc.Text" xml:space="preserve">
    <value>File {0} has unsaved changes. Do you want to save them before closing it?</value>
    <comment>{0} is the placeholder for the file name</comment>
  </data>
```

From these, you would only need to translate the text inside `<value></value>` (the text inside `<comment></comment>` is just a hint for the people translating these strings and does not actually show up in the tool's UI; in most of cases, there won't even be any comment).

Therefore, for each of the target languages (Dutch / German), the process would be as follows:

1. Save a copy of the String.resx file above somewhere locally 
2. Change all `<data><value>...</value></data>` fields from English to the target language
3. Reply to this post and attach the resulting file (do that via GitHub and not via email to ensure the file is attached correctly)

If you still want to try to deal with GitHub yourself directly just let me know and I will try to summarise the process.

**Comment by pplanch** [comment]
Thanks, I’ll pull the file offline and work on that, then post the result. Just to be clear, your latest post mentions translating German and Dutch (which I can do), how about French … is that still relevant ?

**Comment by fernandreu** [comment]
Yeah, sorry, I mixed up the languages in the last post. I meant the two languages you were volunteering for, which are indeed French and Dutch.

**Comment by pplanch** [comment]
Fernando, it's been a while longer than I anticipated, but I managed to complete to my best abilities the French and Dutch language version. Just to allow potential checks for changes since you provided me with the English version, I have included the "original" here as well (which was not changed). One note on the Original (I corrected it in the two other versions) : towards the end of the file, the word "Available" is spelled "Avalilable" and in the corresponding "value" section it says "verison" instead of "version".

I hope to see a better support for Windows on the Parallels Desktop VM's once MacOS Monterey comes out, and maybe will be able to benefit from RibbonX Editor directly ... meanwhile I'm using Ron De Bruin's Excel file to help me with "dynamic" menu's (which is based on your RibbonX I believe).

[RibbonX Original - Dutch - French.zip](https://github.com/fernandreu/office-ribbonx-editor/files/7251309/RibbonX.Original.-.Dutch.-.French.zip)
Let me know if there's anything you need me to check on these translations again ?

Regards
