### ISSUE TITLE
DependencyResolutionException: exception was thrown while activating OfficeRibbonXEditor.ViewModels.Windows.MainWindowViewModel from the WIN10 Explorer

### ISSUE THREAD

**Issue by BerendStorm** [fernandreu/office-ribbonx-editor#177]
When I try to open a WORD template/document using the WIN10 Explorer add-in I get the below mentioned error.
This does not happen when I first open the RibbonEditor and than the file.

ERROR:
Autofac.Core.DependencyResolutionException: An exception was thrown while activating OfficeRibbonXEditor.ViewModels.Windows.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(OfficeRibbonXEditor.Interfaces.IMessageBoxService, OfficeRibbonXEditor.Interfaces.IFileDialogService, OfficeRibbonXEditor.Interfaces.IVersionChecker, OfficeRibbonXEditor.Interfaces.IDialogProvider, OfficeRibbonXEditor.Interfaces.IUrlHelper)' on type 'MainWindowViewModel'. ---> System.Configuration.ConfigurationErrorsException: Kan het configuratiesysteem niet initialiseren ---> System.Configuration.ConfigurationErrorsException: Niet-herkende configuratiesectie userSettings (C:\Users\bstor\AppData\Local\Fernando_Andreu\OfficeRibbonXEditor.exe_Url_ms1ab4w4nmqtiaapfpju3g3yc2fmcqx5\1.7.1.886\user.config line 3)
   bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Configuration.ConfigurationManager.PrepareConfigSystem()
   bij System.Configuration.ConfigurationManager.get_AppSettings()
   bij System.Windows.FrameworkCompatibilityPreferences..cctor()
   --- Einde van intern uitzonderingsstackpad ---
   bij Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   bij Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bij Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- Einde van intern uitzonderingsstackpad ---
   bij Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   bij Autofac.Core.Resolving.InstanceLookup.Execute()
   bij Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bij Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   bij Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   bij Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   bij Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   bij OfficeRibbonXEditor.App.LaunchMainWindow()
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by fernandreu** [comment]
Just realised this is the same issue as #160 so I'm going to close this one
