### ISSUE TITLE
Support for Windows running in a VM on M1 silicon

### ISSUE THREAD

**Issue by JamieG-UK** [fernandreu/office-ribbonx-editor#178]
**Is your feature request related to a problem? Please describe.**
I just tried to install the EXE package on a Windows 11 preview running in a Parallels (17.0.1) VM on an M1 Mac (ARM) and got the message "This program can only be installed on versions of Windows designed for the following processor architectures: x64"

**Describe the solution you'd like**
Given the the rest of my tool chain is running ok, is it possible to remove this installer check or is this a actually "huge" challenge to support?

**Describe alternatives you've considered**
Reverting back to the less-featured original project. Don't want to do that if it can be avoided as this fork is much cleaner!

**Additional context**

![image](https://user-images.githubusercontent.com/25979166/133505569-92e0d1b9-6283-4451-8711-4affee6fb5f5.png)
![image](https://user-images.githubusercontent.com/25979166/133505614-697b4c73-c0c8-4931-8984-5e4fe83dc7f8.png)

**Comment by fernandreu** [comment]
Hi @JamieG-UK, unfortunately it isn't just a matter of removing the check in the installer. The entire tool is built targeting x64 specifically right now. Hence, even if the installer let you go ahead, you would face a similar issue when you try to run the tool. You can check that by trying a version of the tool which doesn't require an installer (e.g. [this](https://github.com/fernandreu/office-ribbonx-editor/releases/download/v1.8.0/OfficeRibbonXEditor-NET5-Binaries.zip)).

There are some challenges to do an ARM64 build right now. You can find more details [here](https://github.com/fernandreu/office-ribbonx-editor/issues/174#issuecomment-895550866). There are .NET 6 preview versions I could try already but, unfortunately, there is no Microsoft-hosted agent with a windows ARM64 OS yet. As I do not have a compatible ARM64 device, I cannot do much without that agent. I can suggest the same thing as in that link: trying to do the build yourself and letting me know the issues you find.

Just wondering: do you run into any issues if you try [OfficeRibbonXEditor-NETFramework-Binaries.zip](https://github.com/fernandreu/office-ribbonx-editor/releases/download/v1.8.0/OfficeRibbonXEditor-NETFramework-Binaries.zip) instead? It uses a framework which is very similar to the one used by the original tool. So, if the original one works, this one should either work too or need very little changes.

**Comment by rfn6** [comment]
I think some other x64 applications on Windows 11 are running fine on ARM windows. Isn't there supposed to be an emulation layer? Would really love to get RibbonX working again (I just got a new Mac laptop).

https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/

**Comment by fernandreu** [comment]
I'm just going to close this issue in favour of the other one, #174, where I posted a build that might work fine on ARM64 Windows already.

I am guessing many other programs were in a similar situation where they never expected having to support anything other than x86 / x64 on Windows.

As a side note, I am assuming you'd run into issues if you try the x64 binaries, but nobody has confirmed this yet.
