### ISSUE TITLE
language - Chinese not work

### ISSUE THREAD

**Issue by actforjason** [fernandreu/office-ribbonx-editor#202]

**Comment by elvisw** [comment]
me too.
version information:

```
Version: 1.9.0.1056
Runtime:
 .NET 6.0.1
 Operating System: Microsoft Windows 10.0.19044
```

**Comment by fernandreu** [comment]
Hi both, and sorry for the long delay. It seems there was some issue with the language file for `zn-CH` not being shipped with the tool (https://github.com/dotnet/sdk/issues/11423).

I have fixed that (or rather, I made a workaround) in the following build, which should let you use the tool in Chinese:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1157&view=artifacts&pathAsName=false&type=publishedArtifacts
