### ISSUE TITLE
application. functions not working

### ISSUE THREAD

**Issue by szwarts** [fernandreu/office-ribbonx-editor#205]
**Describe the bug**
application.displayalert is not working when running a function from a ribbon button designed with the office-ribbonx-editor

**To Reproduce**
1. create a button on a custom ribbon
2. create a function in excel vba which deletes a worksheet. add application.displayalert to the function

**Expected behavior**
the code should delete the worksheet without the prompt to confirm deletion.

**Additional context**
I work with version 1.9.0.1056 of the ribbonx editor
i work with Microsoft® Excel® for Microsoft 365 MSO (Version 2201 Build 16.0.14827.20028) 32-bit

**Comment by fernandreu** [comment]
Hi, sorry for the delay. This app does not alter the VBA code in any way, just the ribbon UI which allows you to call code from it. By the sounds of it, your issue was just on the VBA code, so unfortunately I can't do much to help.
