### ISSUE TITLE
Indonesia translation

### ISSUE THREAD

**Issue by aliishaq-zz** [fernandreu/office-ribbonx-editor#206]
Hi, I Already translate in Indonesia Language, How to contribute here? 
Here file translated in Indonesia Language.

Thanks

[Strings_Indonesia.txt](https://github.com/fernandreu/office-ribbonx-editor/files/8450868/Strings_Indonesia.txt)

**Comment by fernandreu** [comment]
Hi @aliishaq-zz, sorry for the long delay.

Thanks for the Translation! I have now added it to the app, so you don't need to worry about anything else.

You can find an updated version of the app with Indonesian available here:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1159&view=artifacts&pathAsName=false&type=publishedArtifacts
