### ISSUE TITLE
Translation to Brazilian Portuguese Language (pt-br)

### ISSUE THREAD

**Issue by Alexcel** [fernandreu/office-ribbonx-editor#209]
Hi,
I want to translate this app to Brazilian Portuguese Language (pt-br) and, as recommended, I opened this issue.
Thanks,

ALeXceL
alexcel@gmail.com

**Comment by fernandreu** [comment]
Hi @Alexcel, thanks for the help!

The easiest option would be to pass me this file back with the Brazilian Portuguese translations instead: [Strings.zip](https://github.com/fernandreu/office-ribbonx-editor/files/8734507/Strings.zip).

So, if you can download that, translate any string you see in English (just the ones within `<data><value>[here]</value></data>` tags), and reply here with the resulting file attached, I can take care of adding it to the tool and making a build with it.

You've probably seen it already but, just in case, [here](https://github.com/fernandreu/office-ribbonx-editor#creating-a-translation-for-a-new-language) is a little more info about the process. You only need to worry about step 4.

Thanks again!

**Comment by Alexcel** [comment]
Hi, Fernando,
Job done. Attached file: Strings_Pt-Br.zip.I think that it's all ok. But let me know if something went wrong, please.
Cheers,ALeXceL 
Oliveira/MG - Brazil

    Em quinta-feira, 19 de maio de 2022 19:18:15 BRT, Fernando Andreu ***@***.***> escreveu:  
 
 


Hi @Alexcel, thanks for the help!

The easiest option would be to pass me this file back with the Brazilian Portuguese translations instead: Strings.zip.

So, if you can download that, translate any string you see in English (just the ones within <data><value>[here]</value></data> tags), and reply here with the resulting file attached, I can take care of adding it to the tool and making a build with it.

You've probably seen it already but, just in case, here is a little more info about the process. You only need to worry about step 4.

Thanks again!

**Comment by fernandreu** [comment]
Hi @Alexcel,

Sorry for the delay. It seems you sent the attachment via email, but GitHub ignores them that way. Could you instead go to the issue on GitHub ([here](https://github.com/fernandreu/office-ribbonx-editor/issues/209)) and reply from there with the same attachment? That should work fine.

Thanks again!

**Comment by Alexcel** [comment]
As recommended, here is the attachment
[Strings_Pt-Br.zip](https://github.com/fernandreu/office-ribbonx-editor/files/8952220/Strings_Pt-Br.zip)
.

**Comment by fernandreu** [comment]
Thanks for that! I have now included the translation in the tool.

You can download a version of the tool which includes that translation from here: https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1161&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Alexcel** [comment]
Hi, Fernando,

 

Thanks for including the translations.

Tried to access the links listed on the page you passed but none of them cause a download.

 

Please check if it is ok or let me know what I’m doing wrong.

 

Cheers

 

ALeXceL

Alexandre Corrêa

 

De: Fernando Andreu ***@***.***> 
Enviada em: quarta-feira, 22 de junho de 2022 14:33
Para: fernandreu/office-ribbonx-editor ***@***.***>
Cc: ALeXceL ***@***.***>; Mention ***@***.***>
Assunto: Re: [fernandreu/office-ribbonx-editor] Translation to Brazilian Portuguese Language (pt-br) (Issue #209)

 

Thanks for that! I have now included the translation in the tool.

You can download a version of the tool which includes that translation from here: https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1161 <https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1161&view=artifacts&pathAsName=false&type=publishedArtifacts> &view=artifacts&pathAsName=false&type=publishedArtifacts
