### ISSUE TITLE
Change ID

### ISSUE THREAD

**Issue by SonGokussj4** [fernandreu/office-ribbonx-editor#32]
**Describe the bug**
When I try to rename (and then ignore the renaming) of the Images, the edit-textbox prevails. It should "delesect the editing" but it's not. Even ESC is ignored.

**To Reproduce**
1. Open Excel file with images (toolbar)
2. Click on an image and select "Change ID"
3. Click on another image.
4. The first image is within textbox.

**Expected behavior**
Should deselect editing.

**Comment by fernandreu** [comment]
Thanks for letting me know! I will see if I can get this fixed today / tomorrow.

**Comment by SonGokussj4** [comment]
No problem. Just noticed there is an "updated office ribbonx editor" (I hate the official one because of the bugs, redrawing and so on) so I'm eager to try it out in next days. :-) Some kind of "template that has everything" would be nice but that would go to the enhancements sections :-) 

Anyway thanks for doing this.

**Comment by fernandreu** [comment]
Glad to hear that! Yes, the redrawing was one of the main things that made me start this project (if I have to end up editing the code in Notepad++, then what I have is not really a code editor). I can't really take much of the credit for improving the code editor though; that mostly comes straight from having used [ScintillaNET](https://github.com/jacobslusser/ScintillaNET).

I have made an update (3a75c6a) that hopefully gets rid of this issue. You can download the development build from [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=127) to check it out.

At the same time, I have discovered that the enter key does not make the textbox go away if the ID you are introducing is incorrect (try anything with a `#` for example). It shouldn't really let you finish editing if you have an incorrect ID to start with. I will create an issue about that too, and try to solve that tomorrow. Definitely some things about icon IDs that I need to polish 😅
