### ISSUE TITLE
editor crashes without a internet connection

### ISSUE THREAD

**Issue by juwens** [fernandreu/office-ribbonx-editor#35]
**Describe the bug**
editor crashes during start without a internet connection.

**To Reproduce**
1. Disconnect all internet connections
2. Start editor
3. client crashes immediately in VersionChecker.CheckVersionAsync

**Expected behavior**
Editor does not crash.

**Additional context**
There can be other reasons for httpClient.GetAsync to fail:
- github is down
- connection timeout due to network or webserver weirdness
- domain not resolved/blacklisted by your dns-server 

**pull request**
https://github.com/fernandreu/office-ribbonx-editor/pull/34

**Comment by fernandreu** [comment]
Fixed in 979ff81 (thanks again!)
