### ISSUE TITLE
Open files by drag and drop

### ISSUE THREAD

**Issue by Martin5001** [fernandreu/office-ribbonx-editor#38]
Opening files and/or inserting images by simply dragging the icon onto the app window would be really convenient. Is faster especially when having only one file and need to do a quick edit.

**Comment by fernandreu** [comment]
Hi, I have added a preliminary version of that in 631bbbc (see the automated build [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=249)). I plan to do a few more tweaks but it will hopefully get the job done for now.
