### ISSUE TITLE
Allow MultiSelect in Insert Icon Dialog

### ISSUE THREAD

**Issue by JonPeltier** [fernandreu/office-ribbonx-editor#39]
When I have to insert icons into a project's Custom UI, there are usually quite a few icons. I sure would like to be able to select more than one at a time in the Insert Icons dialog. Now I have to select one, click OK, then click the Insert Icons icons again, and try to remember which one I just inserted so I don't inadvertently insert it twice.

The old Custom UI Editor must have allowed this, or I would not have felt the pain using this otherwise great new version.

So my request specifically is to set MultiSelect = True for the Insert Icons dialog, so that multiple icons can be selected and therefore inserted in one trip to the dialog.

**Comment by fernandreu** [comment]
Thanks for the feedback! This was a bug really, as the rest of the code was already prepared for that. Fixed in  38f0b61 (check the development build [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=250)).

**Comment by JonPeltier** [comment]
Awesome.
