### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by RichMichaels** [fernandreu/office-ribbonx-editor#52]
**Describe the bug**
Clicking Remove from the right click menu when an icon image name is selected does not work.

**To Reproduce**
1. Insert an Icon into the Custom UI editor
2. Right click on the icon image name
3. Click Remove
4. Note that nothing happens

**Expected behavior**
The selected image file should be deleted.
**Screenshots**
<img width="294" alt="Screen Shot 2019-08-13 at 8 50 15 AM" src="https://user-images.githubusercontent.com/43221912/62943027-84665d80-bda7-11e9-8b97-5fd62a745a96.png">

**Additional context**
Add any other context about the problem. You can copy the version
information from the tool's About dialog here as well.

**Comment by fernandreu** [comment]
Thanks for letting me know!

Actually, none of the context menu actions seem to do anything for me. If you perform them from the top menu, they work fine (there is no delete option there though).

Not sure how I didn't catch that... I will try to fix this today (and improve the automated tests!).

**Comment by RichMichaels** [comment]
Hi Fernando

Thanks for looking into this. I really like and appreciate what you have done with this tool. I’ve been using the original since it was first released or when I need better functionality I built the xml in VSTO.

BTW the Change ID function only works if you press F2. I don’t recall seeing it on the top menu.

From Rich's iPhone

On Aug 13, 2019, at 12:47, Fernando Andreu <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for letting me know!

Actually, none of the context menu actions seem to do anything for me. If you perform them from the top menu, they work fine (there is no delete option there though).

Not sure how I didn't catch that... I will try to fix this today (and improve the automated tests!).

**Comment by fernandreu** [comment]
Thanks for the feedback!

Yes, anything that does not involve clicking on the context menu was still working, including keyboard shortcuts. The [last build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=417&view=artifacts) should have fixed that.

For info, it was an issue with [the Window's DataContext getting assigned to the ContextMenu only once by default](https://www.codeproject.com/Articles/162784/WPF-ContextMenu-Strikes-Again-DataContext-Not-Upda).

Given how this makes all context menus useless, I think it deserves a proper release, so I will trigger it now (v1.5.1).
