### ISSUE TITLE
Running inside a Wine bottle (on Unix)

### ISSUE THREAD

**Issue by section83** [fernandreu/office-ribbonx-editor#53]
This is really outside the normal sort of question but, I can't think of another way to make contact.  If you aren't in a position to help, that's fine.

I am trying to run OfficeRibbonXEditor inside _Wine_ on an Apple iMac.  At present, it's crashing probably because of missing Windows components.  The crashes have been in a Windows 7 environment with .Net version 4.7.2.  

I have attached a copy of a crash report.

[RibbonX_Editor_crash_backtrace.txt](https://github.com/fernandreu/office-ribbonx-editor/files/3518704/RibbonX_Editor_crash_backtrace.txt)

Are you able to help work out which Windows components are missing ?

Thanks.

**Comment by fernandreu** [comment]
Hi section83,

I haven't used Wine in a while, so I'm not sure if I will be of much help. The error also seems of pretty low level and not too related to the code of the tool itself. In fact, the error code seems to be a generic .NET Exception.

Being so generic might also be of help, as somebody might have come across the same issue for a completely different .NET Framework app. Have you seen these pages for example?

- [Unhandled exception: 0xe0434352 in 32-bit code (0x7b83b829)](https://forum.winehq.org/viewtopic.php?f=8&t=18433) for example?
- [[Feature Request] Wine/Linux compatiblity](https://github.com/johanneszab/TumblThree/issues/62)

At some point, I might think about switching from WPF to something another multiplatform GUI (possibly [Avalonia](https://avaloniaui.net/)), using .NET Core instead. This is not going to happen soon though; perhaps WPF will actually be multiplatform by then.

**Comment by section83** [comment]
Many thanks for all this.  No, I've not seen those pages so, I'll have a read.

I've been thinking of working up a macOS version of ORE.  Multiplatform apps for Unix-like environments are common but can be ugly on a Mac (eg. _LibreOffice_).  I want to learn _[Swift](https://swift.org)_ and _[SwiftUI](https://developer.apple.com/xcode/swiftui/)_ so, I'll probably use those. I've only ever used scripting languages (eg. AppleScript, VBA) and so, it'll be a steep learning curve.

Cheers.

**Comment by section83** [comment]
Still haven't been able to get ORE working in Wine.  However, I have got a little bit further.  In the most recent test, ORE wanted to call a link on GitHub.  Here's a copy of the message my outgoing firewall gave:
![Calling GitHub](https://user-images.githubusercontent.com/7471595/63633327-1dd81e00-c68a-11e9-8460-415fb4db6ac3.png)

After I agreed to the connection, ORE did open a window which looked like this:
![Window](https://user-images.githubusercontent.com/7471595/63633335-48c27200-c68a-11e9-99a1-de46e4ae6388.png)

I can't tell if ORE downloaded what it wanted.  Perhaps it was something in Wine although that seems unlikely.  Could that be connected to the crash ?

Thanks.

**Comment by fernandreu** [comment]
That attempt to connect to the GitHub API is to [check the version of the latest release](https://github.com/fernandreu/office-ribbonx-editor/blob/34cb113aac75c7914abe502b7b21755a267f35be/OfficeRibbonXEditor/Services/VersionChecker.cs#L14), and decide whether to show you the _vX.Y.Z available!_ button in the toolbar based on this. I guess I should sign the app in Azure Pipelines to prevent that security warning.

Other than that, the tool should not attempt to make any other kind of connection. Hence, I think this should not be related to any crash in Wine. You could try to disconnect Internet for a moment and see if this makes any difference, but I would not think so. Other than that, I am afraid I might not be able to offer much more help with Wine, sorry.

**Comment by section83** [comment]
Many thanks.  The connection doesn't worry me but suggests the code does start. That might help in diagnosing what's missing from my Wine prefix.  I've asked a question on the CodeWeavers forum which might lead somewhere.  I'll ask on WineHQ when I can get the latest Wine-stable release running.

Cheers.

**Comment by RTommasi27** [comment]
I think this issue may have to do with the fact that it's trying to use a 32-bit dll and Mac OS has stopped supporting that.  i have several older Wine apps that used to work prior to this change (i think in Catalina).
As an alternative, is there a way to recompile this project in Visual Studio that would allow it to run on a Mac?
Cheers
Ruben

**Comment by section83** [comment]
Thanks. I've given up trying to get ORE working on macOS.  I've moved on to Apple Silicon and new dev projects.

Cheers.
