### ISSUE TITLE
Insert Samples

### ISSUE THREAD

**Issue by phossler** [fernandreu/office-ribbonx-editor#59]
[Insert Samples] replaces everything

1. I have many XML code fragments that I re-use and it'd be nice if I could just select a xml fragment file and insert it at the cursor position. Obviously I'd have to be careful and if I were inserting a new <tab> ....... </tab> fragment to make sure I put it between the <tabs> tags and not inside inappropriate group.

2. The older CustomUI editor had a Samples folder that I could add (full replacement) XML files to and then insert, but there doesn't seem to be a Samples folder (that I can find). Adding that and making the location a setting would be useful

**Comment by fernandreu** [comment]
Sounds like a good and relatively straightforward pair of enhancements. I will try to implement them during the weekend.

**Comment by fernandreu** [comment]
The [latest build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=463&view=artifacts) should have both items implemented.

There is a new field in the settings where you can specify multiple paths to either files or folders. Folders are scanned recursively, so you can have multiple subfolders to sort your samples better. Paths are relative to the tool's executable, so you just need to add `Samples` to have the same functionality as the previous tool.

I am closing this issue for now, but feel free to suggest any tweaks to the implementation.
