### ISSUE TITLE
Validation error window not cleared after correction and re-validating

### ISSUE THREAD

**Issue by phossler** [fernandreu/office-ribbonx-editor#71]
1. Enter code with error and validate
2. Error displayed in validation window
3. Correct error
4. Re-validate
5. "Custom .. well formed" msgbox but error displayed in validation window

Probably should always clear (or close) the Validation window before each [Validate]

![Capture](https://user-images.githubusercontent.com/32959671/68404101-061e1b00-014c-11ea-87dc-eae815bd5254.JPG)

**Comment by fernandreu** [comment]
Thanks for the feedback! I have pushed a commit that should close the panel when appropriate. It won't be closed if the XML validation is correct but the panel was showing Find All results; it will just keep showing those. And vice versa: if you have XML errors and Find All does not find anything, the XML errors will keep showing up.
