### ISSUE TITLE
Generate Callbacks

### ISSUE THREAD

**Issue by DeLaguna** [fernandreu/office-ribbonx-editor#75]
Version: 1.5.1.418
Runtime:
 .NET Framework 4.8.4042.0
 Operating System: Microsoft Windows 10.0.18362 

**Describe the bug**
For some reason, after I have added information to my xml, it doesn't generate new callbacks its not generating all of the buttons

**To Reproduce**
Open the file
click generate call backs. I though it might be formatting or whitespace issues but doesn't seem to matter

**Expected behavior**
To generate code for all of the ribbon buttons in all groups included in the xml

**Comment by fernandreu** [comment]
Hi DeLaguna,

In those buttons / additional xml code you are adding, do you also have additional `onXyz="functionName"` attributes as well? The `Generate Callbacks` action only looks at those when showing you some placeholder VBA code, so it won't add any new lines if those attributes do not exist.

For example, this...

```xml
<customUI onLoad="OnCustomUiLoad" xmlns="http://schemas.microsoft.com/office/2006/01/customui">
</customUI>
```

will give you this:

```VB
'Callback for customUI.onLoad
Sub OnCustomUiLoad(ribbon As IRibbonUI)
End Sub
```

But this won't give you any VBA placeholder:

```xml
<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui">
</customUI>
```

Otherwise, if this is not your issue, pass me some example XML files and I can try to find out the exact problem.

**Comment by DeLaguna** [comment]
I validated it and it said it was good, using onAction ..
XML included below.


<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui
<https://mailtrack.io/trace/link/ab78e65e4b89e03213a6a137b76232880268fac8?url=http%3A%2F%2Fschemas.microsoft.com%2Foffice%2F2009%2F07%2Fcustomui&userId=1318677&signature=91e3a7e6dfdd6a5b>
">
<ribbon startFromScratch="false">
<tabs>
<tab id="QSSTNGmenuTab" label="QSSTNG Menu">
<group id="QSSTNGmenuGroup" label="Quote Summary Sheet The New Generation
Menu">

<button id="ReturnBtn"
label="Return"
image="ReturnBtn"
size="large"
onAction="Return2SelectedMain" />

<button id="MainBtn"
label="Main"
image="MainBtn"
size="large"
onAction="Return2MainBtn" />

<button id="LineBtn"
label="Imported Line Items"
image="LineBtn"
size="large"
onAction="Goto_ImportedLineItems" />

<button id="AtomizersBtn"
label="Atomizers"
image="AtomizersBtn"
size="large"
onAction="Goto_Main_Atomizers" />

<button id="DiskBtn"
label="Disk"
image="DiskBtn"
size="large"
onAction="Goto_Main_Disk" />

<button id="TwokBtn"
label="2k"
image="TwokBtn"
size="large"
onAction="Goto_Main_2k" />

<button id="FluidDeliveryBtn"
label="Fluid Delivery"
image="FluidDeliveryBtn"
size="large"
onAction="Goto_Main_FluidDelivery" />

<button id="AddOnsBtn"
label="Addons"
image="AddOnsBtn"
size="large"
onAction="Goto_Main_AddOns" />

<button id="LegacyBtn"
label="Legacy"
image="LegacyBtn"
size="large"
onAction="Goto_Main_LegacyProducts" />

<button id="ExtractionBtn"
label="Extraction"
image="ExtractionBtn"
size="large"
onAction="Extraction" />

<button id="SaveBtn"
label="Save As"
image="SaveBtn"
size="large"
onAction="SaveAs" />

<button id="ClearQtyBtn"
label="Clear Inputs"
image="ClearQtyBtn"
size="large"
onAction="ClearQtyBtn" />

<button id="HideZeroBtn"
label="Hide Zeros"
image="HideZeroBtn"
size="large"
onAction="HideZeroBtn" />

<button id="ShowZeroBtn"
label="Show Zeros"
image="ShowZeroBtn"
size="large"
onAction="ShowZeroBtn" />

<button id="ReviewBtn"
label="Reviewer Button"
image="ReviewBtn"
size="large"
onAction="ReviewBtn" />



</group>
<group id="WebsiteLinksGroup" label="Website Links">

                    <button id="DeVILBISSBtn"
                    label="DeVILBISS"
                    image="DeVILBISS"
                    size="large"
                    onAction="DeVILBISSBtn" />

                    <button id="RansburgBtn"
                    label="Ransburg"
                    image="Ransburg"
                    size="large"
                    onAction="RansburgBtn" />

                    <button id="msBtn"
                    label="ms"
                    image="ms"
                    size="large"
                    onAction="msBtn" />

                    <button id="BGKBtn"
                    label="BGK"
                    image="BGK"
                    size="large"
                    onAction="BGKBtn" />

                    <button id="BinksBtn"
                    label="Binks"
                    image="Binks"
                    size="large"
                    onAction="BinksBtn" />

</group>
<group id="UserShortcutsMenuGroup" label="User Shortcuts">

                    <button id="Calculator1"
                    label="Calculator1"
                    imageMso="Calculator"
                    size="large"
                    onAction="CalculatorBtn1" />

                    <button id="Calculator2"
                    label="Calculator2"
                    imageMso="Calculator"
                    size="large"
                    onAction="CalculatorBtn2" />

                    <button id="Calculator3"
                    label="Calculator3"
                    imageMso="Calculator"
                    size="large"
                    onAction="CalculatorBtn3" />

</group>
</tab>
</tabs>
</ribbon>
</customUI>

**Comment by fernandreu** [comment]
I just pushed a commit that should fix this. You can check the dev build [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=476&view=artifacts).

The issue was with the code preventing duplicated callbacks to show up (e.g. two buttons using the same Sub for the `onAction` callback). The tool was incorrectly checking for duplicates in any attribute and not just callbacks. In your case, you had buttons whose label was identical to their `onAction` callback, hence the issue.

This minimum example shows the issue:

```xml
<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui">
  <ribbon>
    <tabs>

      <tab label="CustomTab">
        <group label="CustomGroup">

            <button
                id="ExtractionBtn"
                label="InsertAnyStringHere"
                image="ExtractionBtn"
                size="large"
                onAction="InsertAnyStringHere" />

        </group>
      </tab>
    </tabs>
  </ribbon>
</customUI>
```
