### ISSUE TITLE
New version: XML text not showing

### ISSUE THREAD

**Issue by EAJS** [fernandreu/office-ribbonx-editor#79]
Version released late Nov19: downloaded; run; file opens. Icons visible, text not visible.  Sorry if this is stupid, but I have tried multiple files / restarts / attempts.

**Comment by fernandreu** [comment]
Hi EAJS,

I am guessing you might be single-clicking on the UI files in the tree view. Can you try to double-click them instead? Right-clicking on them and pressing `Open` should also work. I have updated the release notes to mention this change, sorry if it was unclear.

**Comment by EAJS** [comment]
Thanks Fernando

Yes that works (I was double clicking the xlam file and nothing happened, as you suggested when I clicked the customUI and the xml text opened)

Do I need to do anything to clear the bug report?

Thanks for your work on ribbon editor – I use it regularly and the upgrades are big improvement.

Regards

John Sewell

**Comment by fernandreu** [comment]
Glad to hear that! Don't worry about the bug report, I'll close this issue for you.
