### ISSUE TITLE
.exe in .zip file doesn't open

### ISSUE THREAD

**Issue by DougFletcherGH** [fernandreu/office-ribbonx-editor#82]
**Describe the bug**
I downloaded the .zip file for v1.6.0.493 and extracted all files to a new folder.  Then tried to run the .exe file, but it didn't appear to do anything.

**To Reproduce**
As per description above.

**Expected behavior**
I expected OfficeRibbonXEditor to load.  When I found the previous version's exe file on github, I downloaded it and it ran and it opened OK.

**Screenshots**
No screenshots, 'coz NOTHING happened.

**Comment by fernandreu** [comment]
Hi DougFletcherGH,

Which `.zip` version did you download, [OfficeRibbonXEditor-NETCore.zip](https://github.com/fernandreu/office-ribbonx-editor/releases/download/v1.6/OfficeRibbonXEditor-NETCore.zip) or [OfficeRibbonXEditor-NETFramework.zip](https://github.com/fernandreu/office-ribbonx-editor/releases/download/v1.6/OfficeRibbonXEditor-NETFramework.zip)? The easiest way to tell is: the .NET Framework version comes with a single executable, while the .NET Core one comes with a bunch of additional files.

The .NET Framework version is more stable, so I would go for this one. If the previous release worked, this version should work as well, as the target framework version has not changed. If not:

1. Check that you have .NET Framework 4.6.1 or higher installed
2. Put the `.exe` file into its own separate folder (to ensure other files are not interfering with the launch somehow)

For the (still experimental) .NET Core version to work, you will need to install the [.NET Core Runtime](https://dotnet.microsoft.com/download) first (3.0 or above; I would recommend the latest 3.1). If you indeed want to use this version but still have issues, try to launch it from a command (or PowerShell) prompt this way:

    dotnet path\to\OfficeRibbonXEditor.dll

Note how you pass the path to the `dll` file in the extracted folder, not to the `exe` file. The tool will probably not run this way either, but it should hopefully give you an error message that you can post back in here.

**Comment by DougFletcherGH** [comment]
Hi fernandreu.
Thanks very much for your quick response.
I am sorry for wasting your time.  I simply used the first file under
Assets, which is the .NETCore.zip file.  Now that I read your
introductory text properly, you are quite clear in explaining that I
really would have been better off with the .NetFramework.zip.  I just
tried it, and it works fine.
Sorry again, and thanks for taking the time to explain.
Kind regards,Doug Fletcher

----- Original Message -----

**Comment by fernandreu** [comment]
No problem, glad it worked!
