### ISSUE TITLE
Dark Background

### ISSUE THREAD

**Issue by Jfruiz** [fernandreu/office-ribbonx-editor#92]
It will be very nice if the editor follow the Windows Dark or Light mode or, at least, can present the icon tree with a black background toogle button, so we could see how icons will appear in both possible system configurations.

In any case, thank you very much for keeping this alive.

**Comment by fernandreu** [comment]
Hi Jfruiz,

Thanks for the support! Do you mean something like this?

![image](https://user-images.githubusercontent.com/2480661/74545393-b61bd500-4f40-11ea-9876-54c1deb23be1.png)

Instead, wouldn't it be better if the editor tab (i.e. the one that appears when you double-click it) had better controls such as setting the background color, toggling the transparency grid, etc.? That way, you can view how the icon looks in any resolution and not just the tiny 16x16 thumbnail in the tree view.

![image](https://user-images.githubusercontent.com/2480661/74545743-540f9f80-4f41-11ea-879d-70ca71b895a3.png)

Regards,
Fernando

**Comment by Jfruiz** [comment]
Yes that is what I propose and of course your alternative idea will be a possible solution to see exactly how icons will appear in the ribbon. But a dark shema for full app will be nice too...

Pd. I have text editor window already changed to black Background and clear text.

**Comment by fernandreu** [comment]
My first thought was also having themes for the full application, which is what I was testing in the first screenshot. There are some nice libraries that will do most of the work for you and with several alternatives in terms of themes, but with some things to be tweaked. See how the entire window actually looked:

![image](https://user-images.githubusercontent.com/2480661/74589451-62bb8c80-4ffd-11ea-80e0-5f8f7ac0c519.png)

![image](https://user-images.githubusercontent.com/2480661/74589456-6d762180-4ffd-11ea-9546-c2d37f4d03a1.png)

![image](https://user-images.githubusercontent.com/2480661/74589462-7cf56a80-4ffd-11ea-8a79-21eea95ca6fb.png)

There are some issues that should be easy to fix, such as the help links not looking like actual menu entries. The controls in the settings window will be a bit more challenging; these come from a third party library that directly support this theme, but only in a paid version of the library.

Hence, I will add some controls to the icon tab itself for now, and create an issue to add those themes at a later time (#93).

**Comment by fernandreu** [comment]
You can now download the [latest build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=669&view=artifacts&type=publishedArtifacts) to use the toolbar I added at the bottom of the icon tab:

![image](https://user-images.githubusercontent.com/2480661/74595152-235d6200-5036-11ea-998e-bc6204aebdf5.png)

**Comment by Jfruiz** [comment]
Thank you very much.
