### ISSUE TITLE
Code editing area bug

### ISSUE THREAD

**Issue by presture** [fernandreu/office-ribbonx-editor#95]
**Describe the bug**
The cursor is not visible when the bacground is set to black

![image](https://user-images.githubusercontent.com/61954412/76176014-158c9e00-61ea-11ea-83ae-d2f6b21f0046.png)

**Comment by fernandreu** [comment]
Good catch. I think the most sensible thing to do would be to assign it the normal text color. I have done so in [this build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=714&view=artifacts&type=publishedArtifacts).
